name: Deploy to Alibaba Cloud
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Connect and Deploy
      uses: fifsky/ssh-action@master
      with:
        command: |
            cd Portfolio/
            ls 
            git pull
            pm2 start app
        host: ${{ secrets.HOST }}
        user: root
        key: ${{ secrets.SERVER_SSH_KEY}}
